# Generated by Django 5.2.11 on 2026-02-24 10:53

import MediConnect.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.CharField(default=MediConnect.models.generate_uuid_pk, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('session_key', models.CharField(blank=True, db_index=True, help_text='Session key for anonymous users', max_length=40, null=True)),
                ('name', models.CharField(max_length=255, verbose_name="Nom de l'appareil")),
                ('device_type', models.CharField(blank=True, max_length=100, null=True, verbose_name="Type d'appareil")),
                ('os', models.CharField(blank=True, max_length=100, null=True, verbose_name="Système d'exploitation")),
                ('browser', models.CharField(blank=True, max_length=100, null=True, verbose_name='Navigateur')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User-Agent')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Appareil principal')),
                ('active', models.BooleanField(default=True, verbose_name='Appareil actif')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='Dernière connexion')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
            ],
            options={
                'verbose_name': 'Appareil',
                'verbose_name_plural': 'Appareils',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.CharField(default=MediConnect.models.generate_uuid_pk, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('symptom_cluster', models.CharField(max_length=255)),
                ('doctor_advice', models.TextField()),
                ('recommended_otc', models.CharField(help_text='Safe medications like anti-inflammatories', max_length=200)),
                ('frequency', models.IntegerField(default=1, help_text='How many times this advice was given')),
            ],
        ),
        migrations.CreateModel(
            name='PandemicSignal',
            fields=[
                ('id', models.CharField(default=MediConnect.models.generate_uuid_pk, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('symptom_type', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('occurrence_count', models.PositiveIntegerField()),
                ('alert_level', models.CharField(default='Low', max_length=20)),
                ('last_detected', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.CharField(default=MediConnect.models.generate_uuid_pk, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('PATIENT', 'Patient'), ('ADMIN', 'Admin'), ('DOCTOR', 'Doctor'), ('SUPER_ADMIN', 'Super Admin')], default='PATIENT', max_length=20)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('bio', models.TextField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False, verbose_name='Email vérifié')),
                ('verification_code', models.CharField(blank=True, max_length=6, null=True, verbose_name='Code de vérification')),
                ('verification_code_created_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de création du code')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='mediconnect_user_set', related_query_name='mediconnect_user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='mediconnect_user_set', related_query_name='mediconnect_user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
            },
        ),
        migrations.CreateModel(
            name='IP',
            fields=[
                ('id', models.CharField(default=MediConnect.models.generate_uuid_pk, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('ip', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MediConnect.device')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'IP',
                'verbose_name_plural': 'IPs',
            },
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.CharField(default=MediConnect.models.generate_uuid_pk, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('specialty', models.CharField(max_length=100)),
                ('is_available', models.BooleanField(default=True)),
                ('license_number', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.CharField(default=MediConnect.models.generate_uuid_pk, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('symptoms_description', models.TextField(help_text="User's raw description")),
                ('ai_clarification', models.TextField(blank=True, help_text="AI's summarized/clarified version")),
                ('suggested_medication', models.CharField(blank=True, help_text='OTC medication suggested by IA or Doctor', max_length=200)),
                ('status', models.CharField(choices=[('PENDING', 'Pending (IA Analysis)'), ('TREATED', 'Treated by Doctor'), ('URGENT', 'Urgent Escalation')], default='PENDING', max_length=10)),
                ('is_emergency', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MediConnect.doctorprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='MediConnect_email_451640_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='MediConnect_role_6cd90f_idx'),
        ),
        migrations.AddIndex(
            model_name='ip',
            index=models.Index(fields=['user'], name='MediConnect_user_id_451253_idx'),
        ),
        migrations.AddIndex(
            model_name='ip',
            index=models.Index(fields=['ip'], name='MediConnect_ip_860db9_idx'),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True), ('user__isnull', False)), fields=('user', 'is_primary'), name='unique_primary_device_per_user'),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.CheckConstraint(condition=models.Q(('user__isnull', False), models.Q(('user__isnull', True), models.Q(('session_key__isnull', True), _negated=True)), _connector='OR'), name='device_has_user_or_session'),
        ),
    ]
