# Generated by Django 5.2.11 on 2026-02-24 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediConnect', '0002_alter_user_groups_alter_user_user_permissions'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ForeignKey(blank=True, help_text='The groups this user belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mediconnect_user_set', related_query_name='mediconnect_user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ForeignKey(blank=True, help_text='Specific permissions for this user.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mediconnect_user_set', related_query_name='mediconnect_user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
