# Generated by Django 5.2.11 on 2026-02-25 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediConnect', '0003_remove_user_groups_remove_user_user_permissions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name="Titre de l'annonce")),
                ('content', models.TextField(verbose_name='Message ou Conseil du jour')),
                ('category', models.CharField(choices=[('INFO', 'Information'), ('TIP', 'Conseil Santé'), ('ALERT', 'Alerte Sanitaire')], default='INFO', max_length=50)),
                ('is_active', models.BooleanField(default=True, verbose_name="Afficher sur l'accueil")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Info Accueil',
                'verbose_name_plural': 'Infos Accueil',
            },
        ),
    ]
