# Generated by Django 5.2.11 on 2026-02-25 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediConnect', '0006_alter_appointment_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='ai_clarification',
            field=models.TextField(blank=True, help_text="AI's summarized/clarified version", null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='suggested_medication',
            field=models.CharField(blank=True, help_text='OTC medication suggested by IA or Doctor', max_length=200, null=True),
        ),
    ]
